//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SW_Consultorio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cita
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cita()
        {
            this.Receta = new HashSet<Receta>();
        }
    
        public int CitaID { get; set; }
        public Nullable<System.DateTime> FechaAtencion { get; set; }
        public Nullable<System.TimeSpan> InicioAtencion { get; set; }
        public Nullable<System.TimeSpan> FinAtencion { get; set; }
        public string Obervacion { get; set; }
        public int MedicoID { get; set; }
        public int PacienteID { get; set; }
        public int UsusarioID { get; set; }
        public int EstadoCitaID { get; set; }
    
        public virtual Estado_Cita Estado_Cita { get; set; }
        public virtual Medico Medico { get; set; }
        public virtual Paciente Paciente { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Receta> Receta { get; set; }
    }
}
