//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SW_Consultorio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cita
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cita()
        {
            this.Receta = new HashSet<Receta>();
        }
    
        public int CitaID { get; set; }
        public Nullable<System.DateTime> FechaAtencion { get; set; }
        public Nullable<System.TimeSpan> InicioAtencion { get; set; }
        public Nullable<System.TimeSpan> FinAtencion { get; set; }
        public string Obervacion { get; set; }
        public int MedicoID { get; set; }
        public int PacienteID { get; set; }
        public int UsusarioID { get; set; }
        public int EstadoCitaID { get; set; }
    
        public virtual Estado_Cita Estado_Cita { get; set; }
        public virtual Medico Medico { get; set; }
        public virtual Paciente Paciente { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Receta> Receta { get; set; }
    }
}
