//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SW_Consultorio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Historia_Clinica
    {
        public int HistoriaClinicaID { get; set; }
        public string Dni { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public Nullable<bool> Genero { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public Nullable<int> TratamientoID { get; set; }
        public int CitaID { get; set; }
    
        public virtual Cita Cita { get; set; }
        public virtual Tratamiento Tratamiento { get; set; }
    }
}
