//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SW_Consultorio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receta
    {
        public int RecetaID { get; set; }
        public string Medicamento { get; set; }
        public int Cantidad { get; set; }
        public string Dosis { get; set; }
        public int CitaID { get; set; }
        public string Frecuencia { get; set; }
        public string Duracion { get; set; }
    
        public virtual Cita Cita { get; set; }
    }
}
