//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SW_Consultorio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receta
    {
        public int RecetaID { get; set; }
        public string Medicamento { get; set; }
        public int Cantidad { get; set; }
        public string Dosis { get; set; }
        public int CitaID { get; set; }
        public string Frecuencia { get; set; }
        public string Duracion { get; set; }
    
        public virtual Cita Cita { get; set; }
    }
}
